import { type Monaco } from "@monaco-editor/react";

export const handleEditorDidMount = (monaco: Monaco) => {
  // Define custom Mocklyst theme
  monaco.editor.defineTheme("mocklyst-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      // JSON specific highlighting
      { token: "string.key.json", foreground: "#06d6a0" },
      { token: "string.value.json", foreground: "#f77f00" },
      { token: "number.json", foreground: "#fcbf49" },
      { token: "keyword.json", foreground: "#8338ec" },
      
      // JavaScript/Python syntax
      { token: "keyword", foreground: "#8338ec" },
      { token: "string", foreground: "#06d6a0" },
      { token: "number", foreground: "#fcbf49" },
      { token: "comment", foreground: "#6c757d", fontStyle: "italic" },
      { token: "identifier", foreground: "#e2e8f0" },
      { token: "operator", foreground: "#fb5607" },
      
      // Shell/bash specific
      { token: "keyword.shell", foreground: "#8338ec" },
      { token: "string.shell", foreground: "#06d6a0" },
    ],
    colors: {
      // Main editor colors matching your project's slate theme
      "editor.background": "#0f172a",
      "editor.foreground": "#e2e8f0",
      "editorLineNumber.foreground": "#64748b",
      "editorLineNumber.activeForeground": "#e2e8f0",
      "editor.selectionBackground": "#334155",
      "editor.lineHighlightBackground": "#1e293b",
      "editor.inactiveSelectionBackground": "#334155",
      
      // Scrollbar colors
      "scrollbar.shadow": "#0f172a",
      "scrollbarSlider.background": "#47556980",
      "scrollbarSlider.hoverBackground": "#64748b80",
      "scrollbarSlider.activeBackground": "#94a3b880",
      
      // Widget colors
      "editorWidget.background": "#0f172a",
      "editorWidget.border": "#475569",
      "editorHoverWidget.background": "#1e293b",
      "editorHoverWidget.border": "#475569",
      
      // Suggestion widget
      "editorSuggestWidget.background": "#1e293b",
      "editorSuggestWidget.border": "#475569",
      "editorSuggestWidget.selectedBackground": "#334155",
      
      // Cursor and selections
      "editorCursor.foreground": "#06d6a0",
      "editor.findMatchBackground": "#8338ec40",
      "editor.findMatchHighlightBackground": "#8338ec20",
      
      // Bracket matching
      "editorBracketMatch.background": "#47556940",
      "editorBracketMatch.border": "#475569",
      
      // Gutter colors
      "editorGutter.background": "#0f172a",
      "editorGutter.addedBackground": "#06d6a0",
      "editorGutter.deletedBackground": "#fb5607",
      "editorGutter.modifiedBackground": "#fcbf49",
      
      // Overview ruler
      "editorOverviewRuler.background": "#0f172a",
      "editorOverviewRuler.border": "#475569",
      
      // Minimap
      "minimap.background": "#0f172a",
      
      // Panel and sidebar colors to match your theme
      "panel.background": "#0f172a",
      "panel.border": "#475569",
      "sideBar.background": "#1e293b",
      "sideBar.foreground": "#e2e8f0",
      
      // Activity bar
      "activityBar.background": "#0f172a",
      "activityBar.foreground": "#e2e8f0",
      "activityBarBadge.background": "#8338ec",
      "activityBarBadge.foreground": "#ffffff",
      
      // Status bar
      "statusBar.background": "#0f172a",
      "statusBar.foreground": "#94a3b8",
      
      // Terminal
      "terminal.background": "#0f172a",
      "terminal.foreground": "#e2e8f0",
      "terminal.ansiBlack": "#1e293b",
      "terminal.ansiRed": "#fb5607",
      "terminal.ansiGreen": "#06d6a0",
      "terminal.ansiYellow": "#fcbf49",
      "terminal.ansiBlue": "#3b82f6",
      "terminal.ansiMagenta": "#8338ec",
      "terminal.ansiCyan": "#06b6d4",
      "terminal.ansiWhite": "#e2e8f0",
      "terminal.ansiBrightBlack": "#475569",
      "terminal.ansiBrightRed": "#fb5607",
      "terminal.ansiBrightGreen": "#06d6a0",
      "terminal.ansiBrightYellow": "#fcbf49",
      "terminal.ansiBrightBlue": "#3b82f6",
      "terminal.ansiBrightMagenta": "#8338ec",
      "terminal.ansiBrightCyan": "#06b6d4",
      "terminal.ansiBrightWhite": "#f8fafc",
    },
  });

  // Keep the original OneDarkPro theme as well
  monaco.editor.defineTheme("OneDarkPro", {
    base: "vs-dark",
    inherit: true,
    rules: [],
    colors: {
      "actionBar.toggledBackground": "#525761",
      "activityBar.background": "#23272e",
      "activityBar.foreground": "#d7dae0",
      "activityBarBadge.background": "#4d78cc",
      "activityBarBadge.foreground": "#f8fafd",
      "badge.background": "#23272e",
      "button.background": "#404754",
      "button.secondaryBackground": "#30333d",
      "button.secondaryForeground": "#c0bdbd",
      "checkbox.border": "#404754",
      "debugToolBar.background": "#1e2227",
      descriptionForeground: "#abb2bf",
      "diffEditor.insertedTextBackground": "#00809b33",
      "dropdown.background": "#1e2227",
      "dropdown.border": "#1e2227",
      "editor.background": "#23272e",
      "editor.findMatchBackground": "#d19a6644",
      "editor.findMatchBorder": "#ffffff5a",
      "editor.findMatchHighlightBackground": "#ffffff22",
      "editor.foreground": "#abb2bf",
      "editor.lineHighlightBackground": "#2c313c",
      "editor.selectionBackground": "#67769660",
      "editor.selectionHighlightBackground": "#ffd33d44",
      "editor.selectionHighlightBorder": "#dddddd",
      "editor.wordHighlightBackground": "#d2e0ff2f",
      "editor.wordHighlightBorder": "#7f848e",
      "editor.wordHighlightStrongBackground": "#abb2bf26",
      "editor.wordHighlightStrongBorder": "#7f848e",
      "editorBracketHighlight.foreground1": "#d19a66",
      "editorBracketHighlight.foreground2": "#c678dd",
      "editorBracketHighlight.foreground3": "#56b6c2",
      "editorBracketMatch.background": "#515a6b",
      "editorBracketMatch.border": "#515a6b",
      "editorCursor.background": "#ffffffc9",
      "editorCursor.foreground": "#528bff",
      "editorError.foreground": "#c24038",
      "editorGroup.background": "#181a1f",
      "editorGroup.border": "#181a1f",
      "editorGroupHeader.tabsBackground": "#1e2227",
      "editorGutter.addedBackground": "#109868",
      "editorGutter.deletedBackground": "#9A353D",
      "editorGutter.modifiedBackground": "#948B60",
      "editorHoverWidget.background": "#1e2227",
      "editorHoverWidget.border": "#181a1f",
      "editorHoverWidget.highlightForeground": "#61afef",
      "editorIndentGuide.activeBackground1": "#c8c8c859",
      "editorIndentGuide.background1": "#3b4048",
      "editorInlayHint.background": "#2c313c",
      "editorInlayHint.foreground": "#abb2bf",
      "editorLineNumber.activeForeground": "#abb2bf",
      "editorLineNumber.foreground": "#495162",
      "editorMarkerNavigation.background": "#1e2227",
      "editorOverviewRuler.addedBackground": "#109868",
      "editorOverviewRuler.deletedBackground": "#9A353D",
      "editorOverviewRuler.modifiedBackground": "#948B60",
      "editorRuler.foreground": "#abb2bf26",
      "editorSuggestWidget.background": "#1e2227",
      "editorSuggestWidget.border": "#181a1f",
      "editorSuggestWidget.selectedBackground": "#2c313a",
      "editorWarning.foreground": "#d19a66",
      "editorWhitespace.foreground": "#ffffff1d",
      "editorWidget.background": "#1e2227",
      focusBorder: "#3e4452",
      "gitDecoration.ignoredResourceForeground": "#636b78",
      "input.background": "#1d1f23",
      "input.foreground": "#abb2bf",
      "list.activeSelectionBackground": "#2c313a",
      "list.activeSelectionForeground": "#d7dae0",
      "list.focusBackground": "#323842",
      "list.focusForeground": "#f0f0f0",
      "list.highlightForeground": "#ecebeb",
      "list.hoverBackground": "#2c313a",
      "list.hoverForeground": "#abb2bf",
      "list.inactiveSelectionBackground": "#323842",
      "list.inactiveSelectionForeground": "#d7dae0",
      "list.warningForeground": "#d19a66",
      "menu.foreground": "#abb2bf",
      "menu.separatorBackground": "#343a45",
      "minimapGutter.addedBackground": "#109868",
      "minimapGutter.deletedBackground": "#9A353D",
      "minimapGutter.modifiedBackground": "#948B60",
      "multiDiffEditor.headerBackground": "#21252b",
      "panel.border": "#3e4452",
      "panelSectionHeader.background": "#1e2227",
      "peekViewEditor.background": "#1b1d23",
      "peekViewEditor.matchHighlightBackground": "#29244b",
      "peekViewResult.background": "#22262b",
      "scrollbar.shadow": "#23252c",
      "scrollbarSlider.activeBackground": "#747d9180",
      "scrollbarSlider.background": "#4e566660",
      "scrollbarSlider.hoverBackground": "#5a637580",
      "settings.focusedRowBackground": "#23272e",
      "settings.headerForeground": "#fff",
      "sideBar.background": "#1e2227",
      "sideBar.foreground": "#abb2bf",
      "sideBarSectionHeader.background": "#23272e",
      "sideBarSectionHeader.foreground": "#abb2bf",
      "statusBar.background": "#1e2227",
      "statusBar.debuggingBackground": "#cc6633",
      "statusBar.debuggingBorder": "#ff000000",
      "statusBar.debuggingForeground": "#ffffff",
      "statusBar.foreground": "#9da5b4",
      "statusBar.noFolderBackground": "#1e2227",
      "statusBarItem.remoteBackground": "#4d78cc",
      "statusBarItem.remoteForeground": "#f8fafd",
      "tab.activeBackground": "#23272e",
      "tab.activeBorder": "#b4b4b4",
      "tab.activeForeground": "#dcdcdc",
      "tab.border": "#181a1f",
      "tab.hoverBackground": "#323842",
      "tab.inactiveBackground": "#1e2227",
      "tab.unfocusedHoverBackground": "#323842",
      "terminal.ansiBlack": "#3f4451",
      "terminal.ansiBlue": "#4aa5f0",
      "terminal.ansiBrightBlack": "#4f5666",
      "terminal.ansiBrightBlue": "#4dc4ff",
      "terminal.ansiBrightCyan": "#4cd1e0",
      "terminal.ansiBrightGreen": "#a5e075",
      "terminal.ansiBrightMagenta": "#de73ff",
      "terminal.ansiBrightRed": "#ff616e",
      "terminal.ansiBrightWhite": "#e6e6e6",
      "terminal.ansiBrightYellow": "#f0a45d",
      "terminal.ansiCyan": "#42b3c2",
      "terminal.ansiGreen": "#8cc265",
      "terminal.ansiMagenta": "#c162de",
      "terminal.ansiRed": "#e05561",
      "terminal.ansiWhite": "#d7dae0",
      "terminal.ansiYellow": "#d18f52",
      "terminal.background": "#23272e",
      "terminal.border": "#3e4452",
      "terminal.foreground": "#abb2bf",
      "terminal.selectionBackground": "#abb2bf30",
      "textBlockQuote.background": "#2e3440",
      "textBlockQuote.border": "#4b5362",
      "textLink.foreground": "#61afef",
      "textPreformat.foreground": "#d19a66",
      "titleBar.activeBackground": "#23272e",
      "titleBar.activeForeground": "#9da5b4",
      "titleBar.inactiveBackground": "#23272e",
      "titleBar.inactiveForeground": "#6b717d",
      "tree.indentGuidesStroke": "#ffffff1d",
      "walkThrough.embeddedEditorBackground": "#2e3440",
      "welcomePage.buttonHoverBackground": "#404754",
    },
  });
};
